/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.awt.List;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.beans.PropertyVetoException;
import static java.lang.Thread.sleep;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author PC
 */
public class InterfaceManager extends javax.swing.JFrame {

    /**
     * Creates new form IHM_Manager
     */
    public InterfaceManager(LogicielManager manager) {
        
        //Utilisateur us= new Utilisateur("Jean","jean","manager","Dupond","Jean");
    	this.manager=manager;
      //  manager= new LogicielManager();
    	setVisible(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        DefaultListModel dlmBis= new DefaultListModel();
        dlmBis=manager.recupererListHeurePointe();
        this.dlm=dlmBis;
       
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(Color.YELLOW);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1280, 720));

        jTabbedPane1.setBackground(new java.awt.Color(241, 246, 190));

        jPanel2.setBackground(new java.awt.Color(241, 246, 190));

        /*
        jTable2.setModel(null);
        */

        //Fullfill table
        Vector<Object> columnNames1 = new Vector<Object>();
        Vector<Object> data1 = new Vector<Object>();
        manager.recupererTableStock(columnNames1, data1);
      

        DefaultTableModel model1 = new DefaultTableModel(data1, columnNames1)
        {

            @Override
            public Class getColumnClass(int column)
            {
                for (int row = 0; row < getRowCount(); row++)
                {
                    Object o = getValueAt(row, column);

                    if (o != null)
                    {
                        return o.getClass();
                    }
                }

                return Object.class;
            }
            public boolean isCellEditable(int row,int col){
                return false;
            }

        };
        //modelTable modelTableConfig = new modelTable(data, columnNames);
        jTable2.setModel(model1);
        jTable2.setDefaultRenderer(Object.class, new MyTableCellRenderer());
        jTable2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable2.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // l.setBorder(new LineBorder(Color.black, 1));

                l.setBackground(Color.decode("#C9F1FD"));

                return l;
            }
        });
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(223, 237, 214));

        jTable3.setModel(new TableModelGestion1(
            new Object [][] {

            },
            new String [] {
                "Produit", "Quantite", "Prix Total"
            }
        ));
        jTable3.setDefaultRenderer(Object.class, new MyTableCellRenderer());
        jTable3.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // l.setBorder(new LineBorder(Color.black, 1));

                l.setBackground(Color.decode("#C9F1FD"));

                return l;
            }
        });
        jScrollPane4.setViewportView(jTable3);

        try
        {
            ResultSet rs=manager.getTypeProduit();
            while (rs.next())
            {
                String typeProduit=rs.getString("nomtype");

                dlm2.addElement(typeProduit);
            }

            /*   rs.close();
            stmt.close();
            connection.close();*/
        }
        catch(Exception e)
        {
            System.out.println( e );
        }
        jList2 = new javax.swing.JList();
        jList2.setModel(dlm2);
        jScrollPane5.setViewportView(jList2);

        jTextField3.setText("0");

        jLabel5.setText("Qte");

        jButton4.setText("Ajouter");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jButton4))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        jButton5.setText("Commander");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Annuler");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(223, 237, 214));

        jTable4.setModel(new TableModelGestion2(
            new Object [][] {

            },
            new String [] {
                "Produit", "Numero Commande", "Quantite", "Prix Total"
            }
        ));
        manager.recupererTableLivraison(jTable4);
      
        jTable4.setDefaultRenderer(Object.class, new MyTableCellRenderer());
        jTable4.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // l.setBorder(new LineBorder(Color.black, 1));

                l.setBackground(Color.decode("#C9F1FD"));

                return l;
            }
        });
        jScrollPane6.setViewportView(jTable4);

        jButton7.setText("Valider Livraison");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Annuler");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 436, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8)
                .addGap(98, 98, 98))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6)
                                .addGap(57, 57, 57))
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );

        JPanel panelHaut = new PanelInformation(this);
        panelHaut.setBounds(750, 10, 400, 30);
        jPanel2.add(panelHaut);

        jTabbedPane1.addTab("Gestion des stocks", jPanel2);

        jPanel1.setBackground(new java.awt.Color(241, 246, 190));
        /*
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        */

        //Object[][] data = {             };
        //String  title[] = {"Produit", "Seuil cuisson HP", "Seuil cuisson HN", "Nombre produit a cuire HP","Nombre produit a cuire HN","Prix"};
        //modelTable modelTableConfig = new modelTable(data, title);

        //Fullfill table
        Vector<Object> columnNames = new Vector<Object>();
        Vector<Object> data = new Vector<Object>();
        manager.recupererTableConfig(columnNames, data);
        
        DefaultTableModel model = new DefaultTableModel(data, columnNames)
        {

            @Override
            public Class getColumnClass(int column)
            {
                for (int row = 0; row < getRowCount(); row++)
                {
                    Object o = getValueAt(row, column);

                    if (o != null)
                    {
                        return o.getClass();
                    }
                }

                return Object.class;
            }
            public boolean isCellEditable(int row,int col){
                if(getValueAt(row, 7).toString().equals("Boisson") && col==2) return false;
                return true;
            }

        };
        //modelTable modelTableConfig = new modelTable(data, columnNames);
        jTable1.setModel(model);
        jTable1.setDefaultRenderer(Object.class, new MyTableCellRenderer());
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jTable1.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                jTable1VetoableChange(evt);
            }
        });
        jTable1.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // l.setBorder(new LineBorder(Color.black, 1));

                l.setBackground(Color.decode("#C9F1FD"));

                return l;
            }
        });
        jTable1.getColumnModel().getColumn(7).setCellEditor(new DefaultCellEditor(new JComboBox<String>(new String[]{"Boisson","Viennoiserie"})));
        jScrollPane1.setViewportView(jTable1);

        jPanel3.setBackground(new java.awt.Color(223, 237, 214));

        jLabel1.setText("Ajout d'une heure de pointe");

        jLabel2.setText("Debut");

        jLabel3.setText("Fin");

        jButton1.setBackground(new java.awt.Color(218, 202, 251));
        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("00:00:00");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("00:00:00");

        jList1.setModel(dlm);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jLabel4.setText("Choisir heure pointe");

        jButton3.setBackground(new java.awt.Color(218, 202, 251));
        jButton3.setText("Supprimer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(35, 35, 35))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(243, 243, 243))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jTextField2))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(31, 31, 31)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jButton2.setBackground(new java.awt.Color(218, 202, 251));
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(198, 198, 198)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(1167, 1167, 1167))
        );

        JPanel panelHaut1 = new PanelInformation(this);
        panelHaut1.setBounds(750, 10, 400, 30);
        jPanel1.add(panelHaut1);

        jTabbedPane1.addTab("Configuration", jPanel1);

        jPanel7.setBackground(new java.awt.Color(241, 246, 190));

        jPanel8.setBackground(new java.awt.Color(223, 237, 214));

        jLabel6.setText("Statistique Global");

        jTable5.setModel(new TableModelStat1(
            new Object [][] {

            },
            new String [] {
                "", "Produits Vendus", "Produits Jetes", "Produits Perdus"
            }
        ));
        int prodVendus=0,prodJetes=0,prodPerdus=0;
        int prodVendusSem=0,prodJetesSem=0,prodPerdusSem=0;
        int prodVendusMois=0,prodJetesMois=0,prodPerdusMois=0;
        int prodVendusAn=0,prodJetesAn=0,prodPerdusAn=0;
        try
        {
            
            ResultSet rs=manager.prodVendu1();
            //  Get row data
            while (rs.next())
            {
                prodVendus=rs.getInt("nbrProd");
            }

            
            rs=manager.prodVendu2();
            
            while (rs.next())
            {
                prodVendusSem=rs.getInt("nbrProd");
            }

            
            rs=manager.prodVendu3();
            //  Get row data
            while (rs.next())
            {
                prodVendusMois=rs.getInt("nbrProd");
            }

           
            rs=manager.prodVendu4();
            //  Get row data
            while (rs.next())
            {
                prodVendusAn=rs.getInt("nbrProd");
            }

            ///////////////////
            /////PROD JETES////
            //////////////////
            
            rs=manager.prodJet1();
            //  Get row data
            while (rs.next())
            {
                prodJetes=rs.getInt("nbrProdJet");

            }

            
            rs=manager.prodJet2();
            //  Get row data
            while (rs.next())
            {
                prodJetesSem=rs.getInt("nbrProdJet");
            }

            
            rs=manager.prodJet3();
            //  Get row data
            while (rs.next())
            {
                prodJetesMois=rs.getInt("nbrProdJet");
            }

            
            rs=manager.prodJet4();
            //  Get row data
            while (rs.next())
            {
                prodJetesAn=rs.getInt("nbrProdJet");
            }

            ///////////////////
            /////PROD PERDUS////
            //////////////////
           
            rs=manager.prodPerdu1();
            //  Get row data
            while (rs.next())
            {
                prodPerdus=rs.getInt("nbrProdPerdus");
            }

           
            rs=manager.prodPerdu2();
            //  Get row data
            while (rs.next())
            {
                prodPerdusSem=rs.getInt("nbrProdPerdus");
            }

          
            rs=manager.prodPerdu3();
            //  Get row data
            while (rs.next())
            {
                prodPerdusMois=rs.getInt("nbrProdPerdus");
            }

            
            rs=manager.prodPerdu4();
            //  Get row data
            while (rs.next())
            {
                prodPerdusAn=rs.getInt("nbrProdPerdus");
            }

            Object[] donnee = new Object[]
            {"Aujourd'hui", prodVendus ,prodJetes,prodPerdus };
            ((TableModelStat1)jTable5.getModel()).addRow(donnee);

            Object[] donnee1 = new Object[]
            {"Semaine", prodVendusSem ,prodJetesSem,prodPerdusSem };
            ((TableModelStat1)jTable5.getModel()).addRow(donnee1);

            Object[] donnee2 = new Object[]
            {"Mois", prodVendusMois ,prodJetesMois,prodPerdusMois };
            ((TableModelStat1)jTable5.getModel()).addRow(donnee2);

            Object[] donnee3 = new Object[]
            {"Annee", prodVendusAn ,prodJetesAn,prodPerdusAn};
            ((TableModelStat1)jTable5.getModel()).addRow(donnee3);

            rs.close();

        }
        catch(Exception e)
        {
            System.out.println( e );
        }
        jTable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable5MouseClicked(evt);
            }
        });
        jTable5.setDefaultRenderer(Object.class, new MyTableCellRenderer());

        jTable5.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {

                JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                // l.setBorder(new LineBorder(Color.black, 1));

                l.setBackground(Color.decode("#C9F1FD"));

                return l;
            }
        });
        jScrollPane7.setViewportView(jTable5);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(223, 237, 214));

        jLabel7.setText("Statistique par vendeur");

        jTable6.setModel(new TableModelStat2(
            new Object [][] {

            },
            new String [] {
                "Employe", "Aujourd'hui", "Semaine", "Mois","Annee"
            }
        ));
        HashMap<String,Integer> hm1= new HashMap<String,Integer>();
        HashMap<String,Integer> hm2= new HashMap<String,Integer>();
        HashMap<String,Integer> hm3= new HashMap<String,Integer>();
        HashMap<String,Integer> hm4= new HashMap<String,Integer>();
        try
        {
            
            ResultSet rs=manager.UserVente1();
            //  Get row data
            while (rs.next())
            {
                String user=rs.getString("user");
                int nbrProd=rs.getInt("nbrProd");
                hm1.put(user, nbrProd);
            }

            
            rs=manager.UserVente2();
            //  Get row data
            while (rs.next())
            {
                String user=rs.getString("user");
                int nbrProd=rs.getInt("nbrProd");
                hm2.put(user, nbrProd);
            }

           
            rs=manager.UserVente3();
            //  Get row data
            while (rs.next())
            {
                String user=rs.getString("user");
                int nbrProd=rs.getInt("nbrProd");
                hm3.put(user, nbrProd);
            }

          
            rs=manager.UserVente4();
            //  Get row data
            while (rs.next())
            {
                String user=rs.getString("user");
                int nbrProd=rs.getInt("nbrProd");
                hm4.put(user, nbrProd);
            }

            rs.close();
          
        }
        catch(Exception e)
        {
            System.out.println( e );
        }
        
        ArrayList listUser=new ArrayList();
        try
        {
            
                ResultSet  rs=manager.getVendeur();
                //  Get row data

                while (rs.next())
                {
                    String u=rs.getString("identifiant");
                    listUser.add(u);
                }

                
            }
            catch(Exception e)
            {
                System.out.println( e );
            }

            for(Iterator itUser=listUser.iterator(); itUser.hasNext();) {
                String vendeur=(String)itUser.next();
                if(hm1.containsKey(vendeur)==false){
                    hm1.put(vendeur, 0);
                }
                if(hm2.containsKey(vendeur)==false){
                    hm2.put(vendeur, 0);
                }
                if(hm3.containsKey(vendeur)==false){
                    hm3.put(vendeur, 0);
                }
                if(hm4.containsKey(vendeur)==false){
                    hm4.put(vendeur, 0);
                }
                Object[] donnee = new Object[]
                {vendeur, hm1.get(vendeur), hm2.get(vendeur),hm3.get(vendeur),hm4.get(vendeur)};
                ((TableModelStat2)jTable6.getModel()).addRow(donnee);
            }

            jTable6.setDefaultRenderer(Object.class, new MyTableCellRenderer());

            jTable6.getTableHeader().setDefaultRenderer(new DefaultTableCellRenderer() {

                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                    boolean isSelected, boolean hasFocus, int row, int column) {

                    JLabel l = (JLabel) super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                    // l.setBorder(new LineBorder(Color.black, 1));

                    l.setBackground(Color.decode("#C9F1FD"));

                    return l;
                }
            });
            jScrollPane8.setViewportView(jTable6);

            javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
            jPanel9.setLayout(jPanel9Layout);
            jPanel9Layout.setHorizontalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel7)
                .addComponent(jScrollPane8)
            );
            jPanel9Layout.setVerticalGroup(
                jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addComponent(jLabel7)
                    .addGap(7, 7, 7)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addContainerGap())
            );

            jPanel10.setBackground(new java.awt.Color(223, 237, 214));
            jPanel10.setForeground(new java.awt.Color(153, 153, 153));
            jPanel10.setLayout(new java.awt.BorderLayout());

            javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
            jPanel7.setLayout(jPanel7Layout);
            jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
            );
            jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
            );

            JPanel panelHaut2 = new PanelInformation(this);
            panelHaut2.setBounds(750, 10, 400, 30);
            jPanel7.add(panelHaut2);

            jTabbedPane1.addTab("Statistiques", jPanel7);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        //produit,quantite,prixToltal
        
       String produit=(String) jList2.getSelectedValue();
       System.out.println(produit);
    if(produit != null)   { 
     if(isNumeric(jTextField3.getText())){
          int quantite=Integer.parseInt(jTextField3.getText());
        if(quantite!=0){ 
         
            float prixTotal=manager.prixTotal(produit, quantite);
 
        
        Object[] donnee = new Object[]
            {produit, quantite, prixTotal};
        ((TableModelGestion1)jTable3.getModel()).addRow(donnee);
          }
          else{
              
              JOptionPane.showMessageDialog(this,
            "Quantite doit > 0",
            "Insane error",
            JOptionPane.ERROR_MESSAGE);
              
          }
          
          
    }
    
    else{
        JOptionPane.showMessageDialog(this,
    "Not a numeric",
    "Insane error",
    JOptionPane.ERROR_MESSAGE);
    }}
    else {
         JOptionPane.showMessageDialog(this,
    "Veuillez choisir un produit",
    "Insane error",
    JOptionPane.ERROR_MESSAGE);
    }
    
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        
        if(jTable3.getRowCount() > 0){
            //On affiche un message mais vous pourriez faire ce que vous voulez
            
            //On affecte un nouveau libellé à une celulle de la ligne
            ((TableModelGestion1)jTable3.getModel()).removeRow(jTable3.getSelectedRow());
        }
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        Commande cmd= new Commande(new Date());
        int idcmd=cmd.getId();
        //Update Table COMMANDE
        manager.updateCommande(cmd);
         

                
        
             try {
                Thread.sleep(5000);                 //1000 milliseconds is one second.
            } catch(InterruptedException ex) {
                Thread.currentThread().interrupt();
            };
        
        int status=0;
        String typeProd;
        int qte;
        float prixTotal;
        
        ArrayList<Lot> listLot= new ArrayList<Lot>();
        
        
         for(int i=0;i<jTable3.getRowCount();i++){
                // System.out.println(table.getRowCount());

                 typeProd=jTable3.getValueAt(i, 0).toString();
                 qte=(int) jTable3.getValueAt(i,1 );
                 prixTotal=(float) jTable3.getValueAt(i,2 );
                 
                 Lot l=new Lot( cmd, qte, typeProd,status);
                 listLot.add(l);
                 
                 Object[] donnee = new Object[]
                {typeProd, cmd.getId(),qte, prixTotal};
                 ((TableModelGestion2)jTable4.getModel()).addRow(donnee);
                 
                
                 //Update Table Lot
                 manager.updateLot(cmd, status, typeProd, qte);
                
                 
                 
                 
                 
         }
         
          if(jTable3.getRowCount() > 0){
            for (int i = jTable3.getRowCount() - 1; i >= 0; i--) {
            ((TableModelGestion1)jTable3.getModel()).removeRow(i);
            }
        }
          
          JOptionPane.showMessageDialog(this,
                    "Success");
          
          
         
        
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
       int nbrLignes[]=jTable4.getSelectedRows();

      
      
          
         if(jTable4.getRowCount() > 0){
           // ((TableModelGestion1)jTable4.getModel()).removeRow();
            for(int i=0;i<nbrLignes.length;i++){
                // System.out.println(table.getRowCount());
                System.out.println(nbrLignes[i]);
                String nomType=jTable4.getValueAt(nbrLignes[i], 0).toString();
                int numCmd=(int) jTable4.getValueAt(nbrLignes[i], 1);
                int qte =(int) jTable4.getValueAt(nbrLignes[i],2 );
                
                manager.annuleLivraison(nomType, numCmd, qte);
         
                
           
               
            }
             }

       
        
         
 
         Arrays.sort(nbrLignes);
         for(int i = nbrLignes.length - 1; i >= 0; i--){
          ((TableModelGestion2)jTable4.getModel()).removeRow(nbrLignes[i]);
          ((TableModelGestion2)jTable4.getModel()).fireTableRowsDeleted(nbrLignes[i], nbrLignes[i]);
         }
          JOptionPane.showMessageDialog(this,
                    "DELETED");
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
         int nbrLignes[]=jTable4.getSelectedRows();

      
       
         if(jTable4.getRowCount() > 0){
           // ((TableModelGestion1)jTable4.getModel()).removeRow();
            for(int i=0;i<nbrLignes.length;i++){
                // System.out.println(table.getRowCount());
                System.out.println(nbrLignes[i]);
                String nomType=jTable4.getValueAt(nbrLignes[i], 0).toString();
                int numCmd=(int) jTable4.getValueAt(nbrLignes[i], 1);
                int qte =(int) jTable4.getValueAt(nbrLignes[i],2 );              
         System.out.println(nomType);
         System.out.println(numCmd);
         System.out.println(qte);
         manager.valideLivraison(nomType, numCmd, qte);
         
        
            } 
             }

           
       
        
         
 
         Arrays.sort(nbrLignes);
         for(int i = nbrLignes.length - 1; i >= 0; i--){
          ((TableModelGestion2)jTable4.getModel()).removeRow(nbrLignes[i]);
          ((TableModelGestion2)jTable4.getModel()).fireTableRowsDeleted(nbrLignes[i], nbrLignes[i]);
         }
          JOptionPane.showMessageDialog(this,
                    "Success");
          
    }                                        

    private void jTable5MouseClicked(java.awt.event.MouseEvent evt) {                                     
        // TODO add your handling code here:
        
        int select=jTable5.getSelectedRow();
       int vendu=(int) jTable5.getModel().getValueAt(select,1);
       int jete=(int) jTable5.getModel().getValueAt(select,2);
       int perdu=(int) jTable5.getModel().getValueAt(select,3);
       
       DefaultCategoryDataset dataset=new DefaultCategoryDataset();
       dataset.setValue(vendu, "", "Vendus");
       dataset.setValue(jete, "", "Jetes");
       dataset.setValue(perdu, "", "Perdus");
       
       JFreeChart chart= ChartFactory.createBarChart("", "", "", dataset, PlotOrientation.HORIZONTAL, false, false, false);
       CategoryPlot catPlot=chart.getCategoryPlot();
       catPlot.setRangeGridlinePaint(Color.BLACK);
       
       
       ChartPanel charpanel=new ChartPanel(chart);
       
       charpanel.setMaximumDrawWidth(4000);  
// The second step is to set the width of a chart panel.
       charpanel.setPreferredSize(new Dimension(200,100));

       jPanel10.removeAll();
       jPanel10.add(charpanel,BorderLayout.CENTER);
       jPanel10.validate();
       
      
    }                                    

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        int response=JOptionPane.showConfirmDialog(this, "Voulez-vous enregistrer la configuration ?");

        if(response==0){
            try {
                // TODO add your handling code here:
                manager.updateTableConfig(this, jTable1);
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceManager.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        }
        else{
            Vector<Object> columnNames = new Vector<Object>();
            Vector<Object> data = new Vector<Object>();
            manager.recupererTableConfig(columnNames, data);
            DefaultTableModel model = new DefaultTableModel(data, columnNames)
            {

                @Override
                public Class getColumnClass(int column)
                {
                    for (int row = 0; row < getRowCount(); row++)
                    {
                        Object o = getValueAt(row, column);

                        if (o != null)
                        {
                            return o.getClass();
                        }
                    }

                    return Object.class;
                }
                public boolean isCellEditable(int row,int col){
                    if(getValueAt(row, 7).toString().equals("Boisson") && col==2) return false;
                    return true;
                }

            };
            jTable1.setModel(model);
        }

    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:

        int response=JOptionPane.showConfirmDialog(this, "Are you sure?");

        if(response==0){

            HeurePointe hp;
            hp=(HeurePointe) jList1.getSelectedValue();
            HeurePointe hp1=new HeurePointe(hp);
            String debut=hp1.getDebut();
            String fin=hp1.getFin();
            ////DELETE DBB
            System.out.println(debut+" "+fin);
            
            manager.supprHeurePointe(debut, fin);
            dlm.removeElement(hp);
            jList1.setModel(dlm);
            JOptionPane.showMessageDialog(this,
                "DELETED");

        }
        else{
            System.out.println("CANCEL");
        }
    }                                        

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {                                    
        // TODO add your handling code here:
        /*HeurePointe hp;
        hp=(HeurePointe) jList1.getSelectedValue();
        HeurePointe hp1=new HeurePointe(hp);
        System.out.println(hp1);*/
    }                                   

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        String debut=jTextField1.getText();
        String fin=jTextField2.getText();

        if(!isValidDate(debut) || !isValidDate(fin)){
            JOptionPane.showMessageDialog(this,
                "Incorrect Format",
                "Insane error",
                JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            SimpleDateFormat sdf = new SimpleDateFormat("H:mm:ss");
            Date dateDebut = null;
            Date dateFin = null;
            try {
                dateDebut =  sdf.parse(debut);
                dateFin =  sdf.parse(fin);
            } catch (ParseException e) {

            }

            if(dateDebut.after(dateFin)){
                JOptionPane.showMessageDialog(this,
                    "date debut doit < date fin",
                    "Insane error",
                    JOptionPane.ERROR_MESSAGE);
            }
            else{
                String debutTime = sdf.format(dateDebut);
                String finTime = sdf.format(dateFin);

                manager.ajoutHeurePointe(debutTime, finTime);
                HeurePointe hp= new HeurePointe(debutTime,finTime);
                dlm.addElement(hp);
                jList1.setModel(dlm);

             
                JOptionPane.showMessageDialog(this,
                    "Success");
                // HeurePointe hp=new HeurePointe();
            }

        }
    }                                        

    private void jTable1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {                                       
        // TODO add your handling code here:

    }                                      

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {                                   
        // TODO add your handling code here:
    }                                  

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     

    }                                    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceManager(new LogicielManager(new Utilisateur("Jean","jean","manager","Dupond","Jean"))).setVisible(true);
           }
        });
    }
    
    
    public boolean isValidDate( String dateStr ) {

    //    K: hour of the day in am/pm
    //    m: minute of a hour
    // 'on': static text
    //  MMM: name of the month with tree letters
    //   dd: day of the month (you can use just d too)
    SimpleDateFormat df = new SimpleDateFormat("H:mm:ss");

    try {
        System.out.println(df.parse( dateStr ));
        return true;
    } catch ( ParseException exc ) {
      System.out.println("Incorrect format!");
   
    }

    return false;

}

    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration                   
   
    private LogicielManager manager;   
    private static Connection connection =null;
    private DefaultListModel dlm= new DefaultListModel();
    private DefaultListModel dlm2= new DefaultListModel();
    
    private int getColumnByName(JTable table, String name) {
                for (int i = 0; i < table.getColumnCount(); ++i)
                    if (table.getColumnName(i).equals(name))
                        return i;
                return -1;
            }
  
    public static boolean isNumeric(String str)  
        {  
          try  
          {  
            int d =Integer.parseInt(str);  
          }  
          catch(NumberFormatException nfe)  
          {  
            return false;  
          }  
          return true;  
        }
    public LogicielManager getLogicielManager(){
    	return this.manager;
    }
    public class miseAJourDateThread extends Thread {
    private JLabel label;
    boolean running;

    public miseAJourDateThread(JLabel label) {
        this.label = label;
        running = true;
    }

	public void arret() {
        running = false;
    }

    public void run() {
        while (running) {
            try {
                sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
           label.setText(DateFormat.getDateTimeInstance(DateFormat.MEDIUM, DateFormat.MEDIUM).format(new Date()));		
        }
    }
    
}

}